### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by gedw99** [RomanBase/flutter_control#2]
This is very well done.

I am using hive to back my domain model.
It's really great I find.

Would you consider this a good persistence lib for your framework ?
Or do you want to keep it open so anyone can inject what they want ? You basically doing a IOC pattern from what I can see

**Comment by RomanBase** [comment]
I agree that Hive is pretty good for caching complex data models. But currently there is no need to implement Hive into lib, because lib using SharedPreferences to store just one String value..

In Flutter isn't Reflection, so library must stay partly open and let users to bend it for project needs.
And you can easily add Hive to lib's Factory/Injection flow if you can.

I thing in every library/framework is IoC principle :)

**Comment by gedw99** [comment]
Great ! Someone that know IOC pattern.

I am going to use this on our project and contribute back.

I think it needs deeplinking and sharing. It's a pretty important thing for
our project.
Do you want to add ?


Have a nice day.

**Comment by RomanBase** [comment]
From my point of view is IoC just principle, not patter. But it doesn't matter..

And yea, any contribution or plugin is welcomed in Flutter community.
So don't bother to fork any Open Source project and try to create amazing things ;)
